### ISSUE TITLE
Verify claw open/close command working properly when disabled and at startup

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2023#111]
The Operator interface tries to make the robot claw match the switch position.  That does not work as written.  In addition, when the switch is thrown in disabled, when the robot gets enabled the claw doesn't open/close to match the switch.

**Comment by dcowden** [comment]
I believe this is the code in question:

        if (operatorPanel.getHID().getRawButton(RobotConstants.OPERATOR_PANEL.GRIPPER)) {
            CommandScheduler.getInstance().schedule(commandFactory.closeGripperCommand());
        } else {
            CommandScheduler.getInstance().schedule(commandFactory.openGripperCommand());
        }

I think its not working because this code runs during robotInit()-- and the hardware isnt ready yet.

The key question is: are we willing to move the gripper to match the panel at teleop init? 

if so, we could run a command to set gripper based on op panel state at teleop init.

if not, a potentially simple solution is to replace the toggle switch with a momentary button, and have the button toggle the state. that way, its automatically in sync with whichever the inital state is
