### ISSUE TITLE
single measurement system for arm length commands

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2023#177]

**Comment by dcowden** [comment]
do this at the same time as command factory refactors

**Comment by dcowden** [comment]
This is for arm positions. zero should be 'full retract'. out should be the full arm out position, in meters, relative to all the way in ((which is about 0.54 meters)

using the number equal to total distance from the mast doesn't work, because the distance from the mast changed based on elbow angle. Plus, its hard to thnk about. when you're tuning settings, because you ahve to add/subtract the length of the arm
